/**
 * Generated by tsnapi — public API snapshot of `@setemiojo/oxlint-config`
 */
// #region Interfaces
export interface SetemiOjoOptions {
  typescript?: boolean;
  react?: boolean;
  tanstackRouter?: boolean;
  next?: boolean;
  node?: boolean;
  testing?: boolean;
}
// #endregion

// #region Functions
export declare function setemiojo(_?: SetemiOjoOptions): OxlintConfigItem;
// #endregion

// #region Variables
export declare const base: OxlintConfigItem[];
export declare const next: OxlintConfigItem[];
export declare const node: OxlintConfigItem[];
export declare const react: OxlintConfigItem[];
export declare const tanstack: OxlintConfigItem[];
export declare const testing: OxlintConfigItem[];
export declare const typescript: OxlintConfigItem[];
// #endregion

// #region Other
export { OxlintConfigItem }
// #endregion