/**
 * Generated by tsnapi — public API snapshot of `@setemiojo/oxlint-config/oxfmt`
 */
// #region Interfaces
export interface OxfmtOptions {
  printWidth?: number;
  tabWidth?: number;
  useTabs?: boolean;
  semi?: boolean;
  singleQuote?: boolean;
  trailingComma?: "all" | "es5" | "none";
  insertFinalNewline?: boolean;
  sortImports?: boolean;
  sortPackageJson?: boolean;
}
// #endregion

// #region Functions
export declare function oxfmt(_?: OxfmtOptions): Oxfmtrc;
// #endregion