import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const content = `// Generated by scripts/typegen.ts — do not edit manually
export type { OxlintConfig as OxlintConfigItem } from 'oxlint'
`

writeFileSync(path.join(__dirname, '../src/typegen.d.ts'), content)
console.log('Generated src/typegen.d.ts')
