import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const content = `// Generated by scripts/typegen.ts — do not edit manually
import type { defineConfig } from 'oxlint'

type _DefineConfigArg = Parameters<typeof defineConfig>[0]

/**
 * A single item in an oxlint flat config array.
 * Extracted from oxlint's defineConfig signature so config files
 * don't each import directly from oxlint.
 */
export type OxlintConfigItem = _DefineConfigArg extends (infer T)[]
  ? T
  : _DefineConfigArg
`

writeFileSync(path.join(__dirname, '../src/typegen.d.ts'), content)
console.log('Generated src/typegen.d.ts')
