import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const require = createRequire(import.meta.url)

const peers = ['oxlint', 'oxfmt', '@tanstack/eslint-plugin-router'] as const

const versions = Object.fromEntries(
  peers.map((name) => {
    try {
      const pkg = require(`${name}/package.json`) as { version: string }
      return [name, pkg.version]
    }
    catch {
      return [name, null]
    }
  }),
)

const lines = [
  '// Generated by scripts/versiongen.ts — do not edit manually',
  `export const versionsMap = ${JSON.stringify(versions, null, 2)} as const`,
  '',
]

writeFileSync(path.join(__dirname, '../src/versions.ts'), lines.join('\n'))
console.log('Generated src/versions.ts', versions)
