export { base } from "./configs/base.js";
export { typescript } from "./configs/typescript.js";
export { react } from "./configs/react.js";
export { node } from "./configs/node.js";
export { testing } from "./configs/testing.js";
export { next } from "./configs/next.js";
export { tanstack } from "./configs/tanstack.js";
export { setemiojo } from "./factory.js";
export type { SetemiOjoOptions } from "./factory.js";
export type { OxlintConfigItem } from "./typegen.js";
